### ISSUE TITLE
old_old_fval = fk + np.linalg.norm(gk) / 2?

### ISSUE THREAD

**Issue by Geo-LianLiu** [jiangyi15/tf-pwa#63]
Hi, 
I feel  confused about the code 
### old_old_fval = fk + np.linalg.norm(gk) / 2 (line 96 in https://github.com/jiangyi15/tf-pwa/blob/dev/tf_pwa/fit_improve.py)

Could you explain what's the principle behind it? Thank you!

**Comment by jiangyi15** [comment]
The code is just copied from [scipy](https://github.com/scipy/scipy/blob/master/scipy/optimize/_optimize.py#L1311).

**Comment by Geo-LianLiu** [comment]
> 

OK, Thanks!
