### ISSUE TITLE
Problem when using save_root

### ISSUE THREAD

**Issue by zyj0905** [jiangyi15/tf-pwa#69]
I am trying to use save_root to create root file as: "config.plot_partial_wave(smooth=True,save_root=True)". However,  I get the error that "AttributeError: module 'uproot' has no attribute 'newtree'". I have checked uproot has been installed successfully.  The version of uproot is 4.2.2.

Do you have any idea about it?

**Comment by jiangyi15** [comment]
You should use uproot3. Uproot4 does not support saving root file.

**Comment by jiangyi15** [comment]
I find that it has been supported now in new api, I can update it.

**Comment by jiangyi15** [comment]
I have added it https://github.com/jiangyi15/tf-pwa/pull/70, you can have a try now.

**Comment by zyj0905** [comment]
Thank you for your reply! I will try it later.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jiangyi15/tf-pwa"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月9日(星期六) 晚上7:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jiangyi15/tf-pwa] Problem when using save_root (Issue #69)





 
I have added it #70, you can have a try now.

**Comment by zyj0905** [comment]
It works well now! Thank you.
